name: CI

on:
  push:

jobs:
  build-linux:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Build and Execute
        run: |
          ./build_all.sh

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: artifact-linux
          path: Sample_*/build

  build-windows:
    runs-on: windows-2019
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      
      - name: Build and Execute
        run: |
          ./build_all.bat

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: artifact-windows
          path: Sample_*/build
  