name: CI

on:
  push:

jobs:
  build-linux:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Build and Execute
        run: |
          ./build_all.sh

  build-windows:
    runs-on: windows-2019
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      
      - name: Build and Execute
        run: |
          ./build_all.bat

